 -- https://www.dropbox.com/s/9f61ufqjmepjb0y/EstadoMunicipioMexico.sql?dl=0
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(1, 'AF', 'Afganistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(2, 'AX', 'Islas Gland',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(3, 'AL', 'Albania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(4, 'DE', 'Alemania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(5, 'AD', 'Andorra',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(6, 'AO', 'Angola',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(7, 'AI', 'Anguilla',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(8, 'AQ', 'Antártida',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(9, 'AG', 'Antigua y Barbuda',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(10, 'AN', 'Antillas Holandesas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(11, 'SA', 'Arabia Saudí',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(12, 'DZ', 'Argelia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(13, 'AR', 'Argentina',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(14, 'AM', 'Armenia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(15, 'AW', 'Aruba',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(16, 'AU', 'Australia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(17, 'AT', 'Austria',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(18, 'AZ', 'Azerbaiyán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(19, 'BS', 'Bahamas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(20, 'BH', 'Bahréin',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(21, 'BD', 'Bangladesh',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(22, 'BB', 'Barbados',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(23, 'BY', 'Bielorrusia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(24, 'BE', 'Bélgica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(25, 'BZ', 'Belice',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(26, 'BJ', 'Benin',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(27, 'BM', 'Bermudas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(28, 'BT', 'Bhután',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(29, 'BO', 'Bolivia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(30, 'BA', 'Bosnia y Herzegovina',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(31, 'BW', 'Botsuana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(32, 'BV', 'Isla Bouvet',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(33, 'BR', 'Brasil',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(34, 'BN', 'Brunéi',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(35, 'BG', 'Bulgaria',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(36, 'BF', 'Burkina Faso',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(37, 'BI', 'Burundi',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(38, 'CV', 'Cabo Verde',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(39, 'KY', 'Islas Caimán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(40, 'KH', 'Camboya',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(41, 'CM', 'Camerún',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(42, 'CA', 'Canadá',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(43, 'CF', 'República Centroafricana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(44, 'TD', 'Chad',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(45, 'CZ', 'República Checa',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(46, 'CL', 'Chile',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(47, 'CN', 'China',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(48, 'CY', 'Chipre',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(49, 'CX', 'Isla de Navidad',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(50, 'VA', 'Ciudad del Vaticano',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(51, 'CC', 'Islas Cocos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(52, 'CO', 'Colombia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(53, 'KM', 'Comoras',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(54, 'CD', 'República Democrática del Congo',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(55, 'CG', 'Congo',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(56, 'CK', 'Islas Cook',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(57, 'KP', 'Corea del Norte',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(58, 'KR', 'Corea del Sur',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(59, 'CI', 'Costa de Marfil',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(60, 'CR', 'Costa Rica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(61, 'HR', 'Croacia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(62, 'CU', 'Cuba',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(63, 'DK', 'Dinamarca',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(64, 'DM', 'Dominica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(65, 'DO', 'República Dominicana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(66, 'EC', 'Ecuador',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(67, 'EG', 'Egipto',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(68, 'SV', 'El Salvador',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(69, 'AE', 'Emiratos Árabes Unidos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(70, 'ER', 'Eritrea',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(71, 'SK', 'Eslovaquia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(72, 'SI', 'Eslovenia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(73, 'ES', 'España',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(75, 'US', 'Estados Unidos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(76, 'EE', 'Estonia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(77, 'ET', 'Etiopía',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(78, 'FO', 'Islas Feroe',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(79, 'PH', 'Filipinas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(80, 'FI', 'Finlandia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(81, 'FJ', 'Fiyi',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(82, 'FR', 'Francia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(83, 'GA', 'Gabón',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(84, 'GM', 'Gambia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(85, 'GE', 'Georgia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(87, 'GH', 'Ghana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(88, 'GI', 'Gibraltar',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(89, 'GD', 'Granada',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(90, 'GR', 'Grecia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(91, 'GL', 'Groenlandia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(92, 'GP', 'Guadalupe',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(93, 'GU', 'Guam',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(94, 'GT', 'Guatemala',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(95, 'GF', 'Guayana Francesa',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(96, 'GN', 'Guinea',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(97, 'GQ', 'Guinea Ecuatorial',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(98, 'GW', 'Guinea-Bissau',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(99, 'GY', 'Guyana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(100, 'HT', 'Haití',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(101, 'HM', 'Islas Heard y McDonald',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(102, 'HN', 'Honduras',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(103, 'HK', 'Hong Kong',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(104, 'HU', 'Hungría',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(105, 'IN', 'India',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(106, 'ID', 'Indonesia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(107, 'IR', 'Irán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(108, 'IQ', 'Iraq',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(109, 'IE', 'Irlanda',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(110, 'IS', 'Islandia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(111, 'IL', 'Israel',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(112, 'IT', 'Italia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(113, 'JM', 'Jamaica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(114, 'JP', 'Japón',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(115, 'JO', 'Jordania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(116, 'KZ', 'Kazajstán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(117, 'KE', 'Kenia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(118, 'KG', 'Kirguistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(119, 'KI', 'Kiribati',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(120, 'KW', 'Kuwait',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(121, 'LA', 'Laos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(122, 'LS', 'Lesotho',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(123, 'LV', 'Letonia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(124, 'LB', 'Líbano',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(125, 'LR', 'Liberia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(126, 'LY', 'Libia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(127, 'LI', 'Liechtenstein',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(128, 'LT', 'Lituania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(129, 'LU', 'Luxemburgo',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(130, 'MO', 'Macao',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(131, 'MK', 'ARY Macedonia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(132, 'MG', 'Madagascar',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(133, 'MY', 'Malasia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(134, 'MW', 'Malawi',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(135, 'MV', 'Maldivas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(136, 'ML', 'Malí',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(137, 'MT', 'Malta',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(138, 'FK', 'Islas Malvinas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(139, 'MP', 'Islas Marianas del Norte',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(140, 'MA', 'Marruecos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(141, 'MH', 'Islas Marshall',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(142, 'MQ', 'Martinica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(143, 'MU', 'Mauricio',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(144, 'MR', 'Mauritania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(145, 'YT', 'Mayotte',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(146, 'MX', 'México',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(147, 'FM', 'Micronesia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(148, 'MD', 'Moldavia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(149, 'MC', 'Mónaco',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(150, 'MN', 'Mongolia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(151, 'MS', 'Montserrat',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(152, 'MZ', 'Mozambique',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(153, 'MM', 'Myanmar',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(154, 'NA', 'Namibia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(155, 'NR', 'Nauru',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(156, 'NP', 'Nepal',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(157, 'NI', 'Nicaragua',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(158, 'NE', 'Níger',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(159, 'NG', 'Nigeria',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(160, 'NU', 'Niue',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(161, 'NF', 'Isla Norfolk',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(162, 'NO', 'Noruega',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(163, 'NC', 'Nueva Caledonia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(164, 'NZ', 'Nueva Zelanda',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(165, 'OM', 'Omán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(166, 'NL', 'Países Bajos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(167, 'PK', 'Pakistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(168, 'PW', 'Palau',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(169, 'PS', 'Palestina',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(170, 'PA', 'Panamá',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(171, 'PG', 'Papúa Nueva Guinea',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(172, 'PY', 'Paraguay',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(173, 'PE', 'Perú',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(174, 'PN', 'Islas Pitcairn',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(175, 'PF', 'Polinesia Francesa',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(176, 'PL', 'Polonia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(177, 'PT', 'Portugal',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(178, 'PR', 'Puerto Rico',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(179, 'QA', 'Qatar',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(180, 'GB', 'Reino Unido',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(181, 'RE', 'Reunión',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(182, 'RW', 'Ruanda',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(183, 'RO', 'Rumania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(184, 'RU', 'Rusia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(185, 'EH', 'Sahara Occidental',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(186, 'SB', 'Islas Salomón',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(187, 'WS', 'Samoa',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(188, 'AS', 'Samoa Americana',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(189, 'KN', 'San Cristóbal y Nevis',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(190, 'SM', 'San Marino',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(191, 'PM', 'San Pedro y Miquelón',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(192, 'VC', 'San Vicente y las Granadinas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(193, 'SH', 'Santa Helena',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(194, 'LC', 'Santa Lucía',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(195, 'ST', 'Santo Tomé y Príncipe',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(196, 'SN', 'Senegal',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(197, 'CS', 'Serbia y Montenegro',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(198, 'SC', 'Seychelles',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(199, 'SL', 'Sierra Leona',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(200, 'SG', 'Singapur',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(201, 'SY', 'Siria',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(202, 'SO', 'Somalia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(203, 'LK', 'Sri Lanka',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(204, 'SZ', 'Suazilandia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(205, 'ZA', 'Sudáfrica',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(206, 'SD', 'Sudán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(207, 'SE', 'Suecia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(208, 'CH', 'Suiza',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(209, 'SR', 'Surinam',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(210, 'SJ', 'Svalbard y Jan Mayen',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(211, 'TH', 'Tailandia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(212, 'TW', 'Taiwán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(213, 'TZ', 'Tanzania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(214, 'TJ', 'Tayikistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(215, 'IO', 'Territorio Británico del Océano Índico',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(216, 'TF', 'Territorios Australes Franceses',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(217, 'TL', 'Timor Oriental',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(218, 'TG', 'Togo',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(219, 'TK', 'Tokelau',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(220, 'TO', 'Tonga',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(221, 'TT', 'Trinidad y Tobago',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(222, 'TN', 'Túnez',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(223, 'TC', 'Islas Turcas y Caicos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(224, 'TM', 'Turkmenistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(225, 'TR', 'Turquía',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(226, 'TV', 'Tuvalu',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(227, 'UA', 'Ucrania',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(228, 'UG', 'Uganda',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(229, 'UY', 'Uruguay',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(230, 'UZ', 'Uzbekistán',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(231, 'VU', 'Vanuatu',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(232, 'VE', 'Venezuela',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(233, 'VN', 'Vietnam',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(234, 'VG', 'Islas Vírgenes Británicas',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(236, 'WF', 'Wallis y Futuna',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(237, 'YE', 'Yemen',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(238, 'DJ', 'Yibuti',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(239, 'ZM', 'Zambia',NULL);
INSERT INTO `catpaises` (`id`, `iso`, `nombre`, `corto`) VALUES(240, 'ZW', 'Zimbabue',NULL);